project:
  type: website
  output-dir: docs

website:
  title: "SQL Gauntlet | Roberto Antuna"
  repo-actions: none
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Northwind Retail"
        href: northwind_retail.qmd
      - text: "Airlines Analytics"
        href: airlines_analytics.qmd
      - text: "AdventureWorks HR"
        href: adventureworks_hr.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



